// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package sso

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginInfoReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfoReq) Reset()         { *m = LoginInfoReq{} }
func (m *LoginInfoReq) String() string { return proto.CompactTextString(m) }
func (*LoginInfoReq) ProtoMessage()    {}
func (*LoginInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_83c8423b67cc1b65, []int{0}
}
func (m *LoginInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfoReq.Unmarshal(m, b)
}
func (m *LoginInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfoReq.Marshal(b, m, deterministic)
}
func (dst *LoginInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfoReq.Merge(dst, src)
}
func (m *LoginInfoReq) XXX_Size() int {
	return xxx_messageInfo_LoginInfoReq.Size(m)
}
func (m *LoginInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfoReq proto.InternalMessageInfo

func (m *LoginInfoReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// HelloRequest 请求结构
type LoginInfoRsp struct {
	User                 *User        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Resources            []*Resource  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	UserGroupes          []*UserGroup `protobuf:"bytes,3,rep,name=userGroupes,proto3" json:"userGroupes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginInfoRsp) Reset()         { *m = LoginInfoRsp{} }
func (m *LoginInfoRsp) String() string { return proto.CompactTextString(m) }
func (*LoginInfoRsp) ProtoMessage()    {}
func (*LoginInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_83c8423b67cc1b65, []int{1}
}
func (m *LoginInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfoRsp.Unmarshal(m, b)
}
func (m *LoginInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfoRsp.Marshal(b, m, deterministic)
}
func (dst *LoginInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfoRsp.Merge(dst, src)
}
func (m *LoginInfoRsp) XXX_Size() int {
	return xxx_messageInfo_LoginInfoRsp.Size(m)
}
func (m *LoginInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfoRsp proto.InternalMessageInfo

func (m *LoginInfoRsp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginInfoRsp) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *LoginInfoRsp) GetUserGroupes() []*UserGroup {
	if m != nil {
		return m.UserGroupes
	}
	return nil
}

type Resource struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SysName              string   `protobuf:"bytes,4,opt,name=sysName,proto3" json:"sysName,omitempty"`
	Priority             int32    `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Path                 string   `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Permission           string   `protobuf:"bytes,8,opt,name=permission,proto3" json:"permission,omitempty"`
	Available            bool     `protobuf:"varint,9,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_83c8423b67cc1b65, []int{2}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Resource) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetSysName() string {
	if m != nil {
		return m.SysName
	}
	return ""
}

func (m *Resource) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Resource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *Resource) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Gids                 []int32  `protobuf:"varint,4,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_83c8423b67cc1b65, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetGids() []int32 {
	if m != nil {
		return m.Gids
	}
	return nil
}

func (m *User) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type UserGroup struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resources            []int32  `protobuf:"varint,3,rep,packed,name=resources,proto3" json:"resources,omitempty"`
	Available            bool     `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGroup) Reset()         { *m = UserGroup{} }
func (m *UserGroup) String() string { return proto.CompactTextString(m) }
func (*UserGroup) ProtoMessage()    {}
func (*UserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_83c8423b67cc1b65, []int{4}
}
func (m *UserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroup.Unmarshal(m, b)
}
func (m *UserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroup.Marshal(b, m, deterministic)
}
func (dst *UserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroup.Merge(dst, src)
}
func (m *UserGroup) XXX_Size() int {
	return xxx_messageInfo_UserGroup.Size(m)
}
func (m *UserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroup proto.InternalMessageInfo

func (m *UserGroup) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserGroup) GetResources() []int32 {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *UserGroup) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func init() {
	proto.RegisterType((*LoginInfoReq)(nil), "sso.LoginInfoReq")
	proto.RegisterType((*LoginInfoRsp)(nil), "sso.LoginInfoRsp")
	proto.RegisterType((*Resource)(nil), "sso.Resource")
	proto.RegisterType((*User)(nil), "sso.User")
	proto.RegisterType((*UserGroup)(nil), "sso.UserGroup")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_83c8423b67cc1b65) }

var fileDescriptor_api_83c8423b67cc1b65 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8b, 0x13, 0x41,
	0x10, 0xdd, 0xf9, 0xda, 0x9d, 0xa9, 0xc4, 0x45, 0x8b, 0x3d, 0x34, 0x61, 0x95, 0x61, 0x10, 0x19,
	0x10, 0x82, 0x44, 0xf0, 0x07, 0x78, 0x59, 0x04, 0xf1, 0xd0, 0xc1, 0x8b, 0xb7, 0xd9, 0x9d, 0x76,
	0xb7, 0x49, 0x32, 0xdd, 0x76, 0x4d, 0x02, 0xf9, 0x0f, 0xfe, 0x44, 0x7f, 0x8c, 0x74, 0x8d, 0xf3,
	0x91, 0x78, 0xd9, 0xdb, 0xab, 0xd7, 0xaf, 0xeb, 0xf5, 0xeb, 0x2a, 0xc8, 0x2a, 0xab, 0x97, 0xd6,
	0x99, 0xd6, 0x60, 0x44, 0x64, 0x8a, 0xb7, 0x30, 0xff, 0x6a, 0x1e, 0x75, 0xf3, 0xa5, 0xf9, 0x69,
	0xa4, 0xfa, 0x85, 0x37, 0x90, 0xb4, 0x66, 0xa3, 0x1a, 0x11, 0xe4, 0x41, 0x99, 0xc9, 0xae, 0x28,
	0x7e, 0x07, 0x53, 0x19, 0x59, 0x7c, 0x0d, 0xf1, 0x9e, 0x94, 0x63, 0xd5, 0x6c, 0x95, 0x2d, 0x89,
	0xcc, 0xf2, 0x3b, 0x29, 0x27, 0x99, 0xc6, 0xf7, 0x90, 0x39, 0x45, 0x66, 0xef, 0x1e, 0x14, 0x89,
	0x30, 0x8f, 0xca, 0xd9, 0xea, 0x05, 0x6b, 0xe4, 0x3f, 0x56, 0x8e, 0xe7, 0xf8, 0x01, 0x66, 0xfe,
	0xd2, 0x9d, 0x33, 0x7b, 0xab, 0x48, 0x44, 0x2c, 0xbf, 0x1e, 0x5a, 0x32, 0x2f, 0xa7, 0x92, 0xe2,
	0x4f, 0x00, 0x69, 0xdf, 0x09, 0xaf, 0x21, 0xd4, 0x35, 0x3f, 0x24, 0x91, 0xa1, 0xae, 0xf1, 0x25,
	0x44, 0x56, 0xd7, 0x22, 0x64, 0xc2, 0x43, 0x44, 0x88, 0x9b, 0x6a, 0xa7, 0x44, 0xc4, 0x91, 0x18,
	0xa3, 0x80, 0x2b, 0x3a, 0xd2, 0x37, 0x4f, 0xc7, 0x4c, 0xf7, 0x25, 0x2e, 0x20, 0xb5, 0x4e, 0x1b,
	0xa7, 0xdb, 0xa3, 0x48, 0xb8, 0xc9, 0x50, 0xfb, 0x4e, 0xb6, 0x6a, 0x9f, 0xc4, 0x65, 0xd7, 0xc9,
	0x63, 0xcf, 0xb5, 0x47, 0xab, 0xc4, 0x55, 0xc7, 0x79, 0x8c, 0x6f, 0x00, 0xac, 0x72, 0x3b, 0x4d,
	0xa4, 0x4d, 0x23, 0x52, 0x3e, 0x99, 0x30, 0x78, 0x0b, 0x59, 0x75, 0xa8, 0xf4, 0xb6, 0xba, 0xdf,
	0x2a, 0x91, 0xe5, 0x41, 0x99, 0xca, 0x91, 0x28, 0x1c, 0xc4, 0x3e, 0xf8, 0x7f, 0xc9, 0xfa, 0x1c,
	0xe1, 0x24, 0xc7, 0x0d, 0x24, 0xf6, 0xc9, 0x34, 0x7d, 0xb8, 0xae, 0xf0, 0xca, 0x47, 0x5d, 0x93,
	0x88, 0xf3, 0xa8, 0x4c, 0x24, 0xe3, 0x53, 0xcf, 0xe4, 0xdc, 0x73, 0x03, 0xd9, 0xf0, 0xd9, 0xcf,
	0x32, 0xbe, 0x9d, 0x8e, 0x38, 0x62, 0x9f, 0xc9, 0x4c, 0x4f, 0xcc, 0xe2, 0x33, 0xb3, 0xd5, 0x16,
	0x60, 0x4d, 0x66, 0xad, 0xdc, 0x41, 0x3f, 0x28, 0xfc, 0x04, 0xf3, 0x3b, 0xd5, 0x0e, 0xeb, 0x85,
	0xaf, 0x78, 0xf4, 0xd3, 0xad, 0x5c, 0x9c, 0x53, 0x64, 0x8b, 0x0b, 0x7c, 0x07, 0xf3, 0x75, 0x75,
	0x50, 0xfe, 0xd9, 0x7c, 0x6f, 0xdc, 0xc2, 0xc5, 0x08, 0x8b, 0x8b, 0xcf, 0xc9, 0x0f, 0xbf, 0xe9,
	0xf7, 0x97, 0xbc, 0xf5, 0x1f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x93, 0xb5, 0xa1, 0x02,
	0x03, 0x00, 0x00,
}
