// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package sso

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginInfoReq struct {
	BasicRawToken        string   `protobuf:"bytes,1,opt,name=basicRawToken,proto3" json:"basicRawToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginInfoReq) Reset()         { *m = LoginInfoReq{} }
func (m *LoginInfoReq) String() string { return proto.CompactTextString(m) }
func (*LoginInfoReq) ProtoMessage()    {}
func (*LoginInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_426693fff9838fea, []int{0}
}
func (m *LoginInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfoReq.Unmarshal(m, b)
}
func (m *LoginInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfoReq.Marshal(b, m, deterministic)
}
func (dst *LoginInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfoReq.Merge(dst, src)
}
func (m *LoginInfoReq) XXX_Size() int {
	return xxx_messageInfo_LoginInfoReq.Size(m)
}
func (m *LoginInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfoReq proto.InternalMessageInfo

func (m *LoginInfoReq) GetBasicRawToken() string {
	if m != nil {
		return m.BasicRawToken
	}
	return ""
}

// HelloRequest 请求结构
type LoginInfoRsp struct {
	User                 *User        `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Resources            []*Resource  `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	UserGroupes          []*UserGroup `protobuf:"bytes,3,rep,name=userGroupes,proto3" json:"userGroupes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginInfoRsp) Reset()         { *m = LoginInfoRsp{} }
func (m *LoginInfoRsp) String() string { return proto.CompactTextString(m) }
func (*LoginInfoRsp) ProtoMessage()    {}
func (*LoginInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_426693fff9838fea, []int{1}
}
func (m *LoginInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginInfoRsp.Unmarshal(m, b)
}
func (m *LoginInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginInfoRsp.Marshal(b, m, deterministic)
}
func (dst *LoginInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginInfoRsp.Merge(dst, src)
}
func (m *LoginInfoRsp) XXX_Size() int {
	return xxx_messageInfo_LoginInfoRsp.Size(m)
}
func (m *LoginInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginInfoRsp proto.InternalMessageInfo

func (m *LoginInfoRsp) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginInfoRsp) GetResources() []*Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *LoginInfoRsp) GetUserGroupes() []*UserGroup {
	if m != nil {
		return m.UserGroupes
	}
	return nil
}

type Resource struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SysName              string   `protobuf:"bytes,4,opt,name=sysName,proto3" json:"sysName,omitempty"`
	Priority             int32    `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Path                 string   `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Permission           string   `protobuf:"bytes,8,opt,name=permission,proto3" json:"permission,omitempty"`
	Available            bool     `protobuf:"varint,9,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_426693fff9838fea, []int{2}
}
func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (dst *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(dst, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Resource) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetSysName() string {
	if m != nil {
		return m.SysName
	}
	return ""
}

func (m *Resource) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Resource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Resource) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *Resource) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Gids                 []int32  `protobuf:"varint,4,rep,packed,name=gids,proto3" json:"gids,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_426693fff9838fea, []int{3}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetGids() []int32 {
	if m != nil {
		return m.Gids
	}
	return nil
}

func (m *User) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type UserGroup struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resources            []int32  `protobuf:"varint,3,rep,packed,name=resources,proto3" json:"resources,omitempty"`
	Available            bool     `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGroup) Reset()         { *m = UserGroup{} }
func (m *UserGroup) String() string { return proto.CompactTextString(m) }
func (*UserGroup) ProtoMessage()    {}
func (*UserGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_426693fff9838fea, []int{4}
}
func (m *UserGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGroup.Unmarshal(m, b)
}
func (m *UserGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGroup.Marshal(b, m, deterministic)
}
func (dst *UserGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGroup.Merge(dst, src)
}
func (m *UserGroup) XXX_Size() int {
	return xxx_messageInfo_UserGroup.Size(m)
}
func (m *UserGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UserGroup proto.InternalMessageInfo

func (m *UserGroup) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserGroup) GetResources() []int32 {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *UserGroup) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func init() {
	proto.RegisterType((*LoginInfoReq)(nil), "sso.LoginInfoReq")
	proto.RegisterType((*LoginInfoRsp)(nil), "sso.LoginInfoRsp")
	proto.RegisterType((*Resource)(nil), "sso.Resource")
	proto.RegisterType((*User)(nil), "sso.User")
	proto.RegisterType((*UserGroup)(nil), "sso.UserGroup")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SsoServiceClient is the client API for SsoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SsoServiceClient interface {
	GetLoginInfo(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*LoginInfoRsp, error)
	SaveUserInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
}

type ssoServiceClient struct {
	cc *grpc.ClientConn
}

func NewSsoServiceClient(cc *grpc.ClientConn) SsoServiceClient {
	return &ssoServiceClient{cc}
}

func (c *ssoServiceClient) GetLoginInfo(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*LoginInfoRsp, error) {
	out := new(LoginInfoRsp)
	err := c.cc.Invoke(ctx, "/sso.SsoService/GetLoginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ssoServiceClient) SaveUserInfo(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/sso.SsoService/SaveUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsoServiceServer is the server API for SsoService service.
type SsoServiceServer interface {
	GetLoginInfo(context.Context, *LoginInfoReq) (*LoginInfoRsp, error)
	SaveUserInfo(context.Context, *User) (*User, error)
}

func RegisterSsoServiceServer(s *grpc.Server, srv SsoServiceServer) {
	s.RegisterService(&_SsoService_serviceDesc, srv)
}

func _SsoService_GetLoginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsoServiceServer).GetLoginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.SsoService/GetLoginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsoServiceServer).GetLoginInfo(ctx, req.(*LoginInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SsoService_SaveUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsoServiceServer).SaveUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.SsoService/SaveUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsoServiceServer).SaveUserInfo(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _SsoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.SsoService",
	HandlerType: (*SsoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoginInfo",
			Handler:    _SsoService_GetLoginInfo_Handler,
		},
		{
			MethodName: "SaveUserInfo",
			Handler:    _SsoService_SaveUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_426693fff9838fea) }

var fileDescriptor_api_426693fff9838fea = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0xc6, 0xbb, 0xff, 0xda, 0xec, 0x24, 0xad, 0x60, 0xc4, 0xc1, 0x8a, 0x0a, 0x8a, 0x56, 0x08,
	0xad, 0x84, 0x14, 0xa1, 0x80, 0x78, 0x00, 0x2e, 0x15, 0x12, 0xe2, 0xe0, 0xc0, 0x85, 0x9b, 0x93,
	0x35, 0xad, 0xd5, 0x64, 0x6d, 0x3c, 0x9b, 0xa0, 0xbc, 0x03, 0x8f, 0xc8, 0xc3, 0x20, 0x4f, 0xd8,
	0x3f, 0x09, 0x17, 0x6e, 0x9f, 0x7f, 0x1e, 0xcf, 0xe7, 0x6f, 0x3d, 0x0b, 0xb9, 0x72, 0x66, 0xee,
	0xbc, 0x6d, 0x2c, 0x26, 0x44, 0xb6, 0x78, 0x07, 0x93, 0x4f, 0xf6, 0xde, 0xd4, 0x1f, 0xeb, 0xef,
	0x56, 0xea, 0x1f, 0xf8, 0x12, 0xae, 0x57, 0x8a, 0xcc, 0x5a, 0xaa, 0x9f, 0x5f, 0xec, 0xa3, 0xae,
	0x45, 0x34, 0x8b, 0xca, 0x5c, 0x9e, 0xc2, 0xe2, 0x57, 0x34, 0x3c, 0x46, 0x0e, 0x9f, 0x43, 0xba,
	0x23, 0xed, 0xb9, 0x7a, 0xbc, 0xc8, 0xe7, 0x44, 0x76, 0xfe, 0x95, 0xb4, 0x97, 0x8c, 0xf1, 0x35,
	0xe4, 0x5e, 0x93, 0xdd, 0xf9, 0xb5, 0x26, 0x11, 0xcf, 0x92, 0x72, 0xbc, 0xb8, 0xe6, 0x1a, 0xf9,
	0x97, 0xca, 0x7e, 0x1f, 0xdf, 0xc0, 0x38, 0x1c, 0xba, 0xf3, 0x76, 0xe7, 0x34, 0x89, 0x84, 0xcb,
	0x6f, 0xba, 0x96, 0xcc, 0xe5, 0xb0, 0xa4, 0xf8, 0x1d, 0xc1, 0xa8, 0xed, 0x84, 0x37, 0x10, 0x9b,
	0x8a, 0x2f, 0x92, 0xc9, 0xd8, 0x54, 0xf8, 0x04, 0x12, 0x67, 0x2a, 0x11, 0x33, 0x08, 0x12, 0x11,
	0xd2, 0x5a, 0x6d, 0xb5, 0x48, 0x38, 0x1a, 0x6b, 0x14, 0x70, 0x45, 0x07, 0xfa, 0x1c, 0x70, 0xca,
	0xb8, 0x5d, 0xe2, 0x14, 0x46, 0xce, 0x1b, 0xeb, 0x4d, 0x73, 0x10, 0x19, 0x37, 0xe9, 0xd6, 0xa1,
	0x93, 0x53, 0xcd, 0x83, 0xb8, 0x3c, 0x76, 0x0a, 0x3a, 0xb0, 0xe6, 0xe0, 0xb4, 0xb8, 0x3a, 0xb2,
	0xa0, 0xf1, 0x05, 0x80, 0xd3, 0x7e, 0x6b, 0x88, 0x8c, 0xad, 0xc5, 0x88, 0x77, 0x06, 0x04, 0x6f,
	0x21, 0x57, 0x7b, 0x65, 0x36, 0x6a, 0xb5, 0xd1, 0x22, 0x9f, 0x45, 0xe5, 0x48, 0xf6, 0xa0, 0xf0,
	0x90, 0x86, 0xe0, 0xff, 0x24, 0x6b, 0x73, 0xc4, 0x83, 0x1c, 0xcf, 0x20, 0x73, 0x0f, 0xb6, 0x6e,
	0xc3, 0x1d, 0x17, 0xa1, 0xf2, 0xde, 0x54, 0x24, 0xd2, 0x59, 0x52, 0x66, 0x92, 0xf5, 0xa9, 0x67,
	0x76, 0xee, 0xf9, 0x08, 0x79, 0xf7, 0xb1, 0xff, 0xcb, 0xf8, 0x76, 0xf8, 0xc4, 0x09, 0xfb, 0x0c,
	0xde, 0xf4, 0xc4, 0x2c, 0x3d, 0x33, 0x5b, 0x6c, 0x00, 0x96, 0x64, 0x97, 0xda, 0xef, 0xcd, 0x5a,
	0xe3, 0x7b, 0x98, 0xdc, 0xe9, 0xa6, 0x1b, 0x2f, 0x7c, 0xca, 0x4f, 0x3f, 0x9c, 0xd2, 0xe9, 0x39,
	0x22, 0x57, 0x5c, 0xe0, 0x2b, 0x98, 0x2c, 0xd5, 0x5e, 0x87, 0x6b, 0xf3, 0xb9, 0x7e, 0x0a, 0xa7,
	0xbd, 0x2c, 0x2e, 0x3e, 0x64, 0xdf, 0xc2, 0xe4, 0xaf, 0x2e, 0xf9, 0x2f, 0x78, 0xfb, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xd3, 0xa7, 0x02, 0x6f, 0x12, 0x03, 0x00, 0x00,
}
